name: Android Pull Request CI

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'android/**'

defaults:
  run:
    working-directory: ./android

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/test-results/**/*.xml"