name: Android CD

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    working-directory: ./android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Create Properties File
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "$DEBUG_KEYSTORE" | base64 -d > debug.keystore
          echo "$KEYSTORE_PROPERTIES" > keystore.properties
          echo "$LOCAL_PROPERTIES" > local.properties

      - name: Build Release APK
        run: |
          ./gradlew :app:assembleRelease

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: ./android/app/build/outputs/apk/release/
          if-no-files-found: error

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ./android/app/build/outputs/apk/release/*.apk
